### ISSUE TITLE
Scrollview 貌似没解决，滑动嵌套问题，比如Viewpage

### ISSUE THREAD

**Issue by xufeifandj** [huxq17/XRefreshView#1]
上拉的时候没有提升，松手放开的接口。       其他的暂时还没发现。

**Comment by huxq17** [comment]
能问下viewpage具体是什么问题的，松开的接口可以提供，没问题。

**Comment by huxq17** [comment]
松手放开的接口已提供，在demo中有示例

**Comment by xufeifandj** [comment]
![default](https://cloud.githubusercontent.com/assets/3191545/8245606/3115566c-1663-11e5-89fc-485ed3eaab7f.png)
兄弟，我QQ459821731 能请教点。这个个问题的吗。如何更好的解决。

**Comment by huclengyue** [comment]
只能说请打死你们设计，设计的什么东西··

**Comment by huxq17** [comment]
早就解决了，忘了关了
