### ISSUE TITLE
有时下拉刷新时拉一小段距离突然弹回，就好像车爬坡过程中突然脱档了

### ISSUE THREAD

**Issue by Charay** [huxq17/XRefreshView#10]

**Comment by huxq17** [comment]
已经解决 
compile 'com.huxq17.xrefreshview:xrefreshview:2.1.5'

**Comment by Charay** [comment]
多谢楼主，解决好快。



charay@126.com
 
发件人： huxq17
发送时间： 2016-04-14 16:07
收件人： huxq17/XRefreshView
抄送： Charay
主题： Re: [huxq17/XRefreshView] 有时下拉刷新时拉一小段距离突然弹回，就好像车爬坡过程中突然脱档了 (#10)
已经解决 
compile 'com.huxq17.xrefreshview:xrefreshview:2.1.5'
