### ISSUE TITLE
onlayout 耗时130ms+

### ISSUE THREAD

**Issue by zhangchaojiong** [huxq17/XRefreshView#101]
onlayout 耗时130ms+ 有轻微卡卡顿。需要优化！

**Comment by huxq17** [comment]
怎么测量的130ms？是不是被XRefreshview刷新的布局的onlayout里做了很多操作？

**Comment by zhangchaojiong** [comment]
用android.support.v4.view.ViewPager 嵌套了 XRefreshView，chalid.layout 的时候 调用了RecycleView 的onBindViewHolder。 每一次滑动Viewpager 的时候都会去重新执行 layout ->onBindViewHolder.如果是ListView 的话。 每一次滑动Viewpager 的时候都会去重新执行 layout （但不会执行getView）。所以我怀疑是Viewpage 和RecycleView  的兼容不好！楼主有试过这个问题吗？

**Comment by huxq17** [comment]
能给个你的示例么？

**Comment by zhangchaojiong** [comment]
不好意思通过排查是我 调用了notifydatachange。。我的问题。可以关闭此issue
