### ISSUE TITLE
RecyclerView里面控件左右滑动与headView下拉事件冲突

### ISSUE THREAD

**Issue by wsy858** [huxq17/XRefreshView#11]
我的RecyclerView里面控件需要左右滑动，当我带有一定倾斜角度左右滑动时候，会同时触发HEAD向下移动一定距离，拦截我左右滑动事件，我希望左右滑动head不向下移动，请问如何解决这种冲突？

**Comment by huxq17** [comment]
你有在代码里添加下面这行代码么？
xRefreshView.setMoveForHorizontal(true);

**Comment by wsy858** [comment]
有添加的，正常是可以左右滑动，但是带有倾斜角度，比如45度角从右向左滑动就会触发headView下移动一点点距离，这时候水平滑动就不能成功顺畅完成，是否可以设置在我左右滑动开始禁用head下拉滑动，左右滑动完成又开启

**Comment by huxq17** [comment]
45度角这样滑动，水平方向也会滑动？和demo里BannerRecyclerViewActivity的效果是一样的么？

**Comment by wsy858** [comment]
说错了，45度是不行的。我这边是RecyclerView的item为自定义滑动控件，试了下差不多大于45度多，小于60度，就会有点冲突，会轻微触发headView下滑一点距离。

**Comment by huxq17** [comment]
大于45度，用户的意图已经是上下滑动了，headerview下滑应该属于正常情况，此时自定义滑动控件也会水平滑动？

**Comment by wsy858** [comment]
是的会滑动一定距离，然后就被MotionEvent.ACTION_CANCEL，我看下从水平控件去屏蔽吧，谢谢了！

**Comment by huxq17** [comment]
你要是有时间，写个demo给我看下，感觉问题不大

**Comment by wsy858** [comment]
OK

**Comment by wsy858** [comment]
这个问题已经解决
水平滑动监听，MotionEvent.ACTION_MOVE的时候，
((XRefreshView) recyclerView.getParent()).disallowInterceptTouchEvent(true); 

水平滑动监听，MotionEvent.ACTION_UP或者MotionEvent.ACTION_CANCEL的时候
 ((XRefreshView) recyclerView.getParent()).disallowInterceptTouchEvent(false);

**Comment by huxq17** [comment]
ok
