### ISSUE TITLE
listview的问题

### ISSUE THREAD

**Issue by tangoox** [huxq17/XRefreshView#12]
下载了你的demo，在listviewactivity试了一下 发现如果把上拉下拉都设置为true 那么上拉第二次以后下拉就无法使用了，上拉的loading也一直在转。请问这个要怎么弄呢
// 设置是否可以下拉刷新
refreshView.setPullRefreshEnable(true);
// 设置是否可以上拉加载
refreshView.setPullLoadEnable(true);

**Comment by tangoox** [comment]
如果上拉一次，下拉页无法使用

**Comment by tangoox** [comment]
`[](url)`

**Comment by huxq17** [comment]
你看看别的activity，会有个stop的方法

**Comment by tangoox** [comment]
refreshView.stopRefresh();
refreshView.stopLoadMore();
就是这两个方法嘛，我直接在你的代码里面改的，你的这个页面也写上这两个方法的。

**Comment by huxq17** [comment]
已经解决了，你再看看
