### ISSUE TITLE
调用startrefresh()异常

### ISSUE THREAD

**Issue by lijiaheng152** [huxq17/XRefreshView#129]
在调用startRefresh()方法时，在顶部会同时显示refreshView(刷新的头布局)和loadMore(加载更多的底部布局)

**Comment by huxq17** [comment]
列表有数据么

**Comment by lijiaheng152** [comment]
有数据  em·· 有点奇怪 是在viewpager+fragment， viewpager共四页，在其他三页显示正常  只有切换到第四页的时候会出现这种情况

**Comment by lijiaheng152** [comment]
我再 fragment的 onResume()和setUserVisibleHint()方法中都调用了startRefresh方法

**Comment by huxq17** [comment]
能给个小demo看看么，发我邮箱就好

**Comment by lijiaheng152** [comment]
打扰大佬了 ，是我写法有问题，我的XRefreshView的height设置的是wrap_content,设置为match_parent之后正常显示

**Comment by huxq17** [comment]
ok
