### ISSUE TITLE
判断当前xRefreshView是否正在刷新的方法

### ISSUE THREAD

**Issue by FTExplore** [huxq17/XRefreshView#14]
好像只有view自带的isShown isActivited等,建议作者加一个isRefreshing()，可以判断当前的xRefreshView是否正在执行onRefresh

**Comment by huxq17** [comment]
是否正在刷新是：xrefreshview.mPullRefreshing 
是否正在加载更多是：xrefreshview.mPullLoading

**Comment by FTExplore** [comment]
哦，好的，谢谢，您做的这个框架真不错，使用简便，稳定，赞一个！
