### ISSUE TITLE
关于事件分发的问题

### ISSUE THREAD

**Issue by FTExplore** [huxq17/XRefreshView#16]
目前的情况是, 我想在某些场合，例如，我的一个ListView中的一个item的滑动事件发生的时候，不触发xrefreshview的下拉事件，请问有类似的解决方案吗？谢谢

**Comment by huxq17** [comment]
看看这个 #11

**Comment by FTExplore** [comment]
嗯，反馈一下，我上个礼拜尝试了几种办法，后来选择的解决方案是，在onTouch那里，通过判断一个全局的静态变量，用于拦截事件的分发，当我的listview的左右滑动正在进行的时候，把一个全局变量(一个boolean)设置一下，这么处理不是很优雅，还需要继续研究

**Comment by huxq17** [comment]
我在整理XRefreshView代码的时候，发现之前有提供这个方法，如果不想让XRefreshView拦截事件，可以调用这个方法并传入true 
/**
     * if child need the touch event,pass true
     */
    public void disallowInterceptTouchEvent(boolean isIntercept) {
        mIsIntercept = isIntercept;
    }
