### ISSUE TITLE
如何实现自定义header和footer

### ISSUE THREAD

**Issue by jinguoliang** [huxq17/XRefreshView#2]
您好,您的这个下拉刷新很好,但是我做得项目想要自定义header和footer,请问如何自定义呢?

**Comment by huxq17** [comment]
目前还没提供接口，后续会有，现在可以自行修改xrefreshview_header.xml和xrefreshview_footer.xml

**Comment by huxq17** [comment]
已经提供了，setCustomHeaderView和setCustomFooterView，具体用法请参考
[我的博客](http://blog.csdn.net/footballclub/article/details/46982115 "description")

**Comment by SSOOnline** [comment]
作者碉堡了
