### ISSUE TITLE
关于baserecyclerviewadapter

### ISSUE THREAD

**Issue by 1181631922** [huxq17/XRefreshView#21]
@Override
    public final int getItemViewType(int position) {
        if (isHeader(position)) {
            return VIEW_TYPES.HEADER;
        } else if (isFooter(position)) {
            return VIEW_TYPES.FOOTER;
        } else {
            position = getStart() > 0 ? position - 1 : position;
            return getAdapterItemViewType(position);
        }
    }
这定义为final我感觉有点不合理，如果我需要根据这个去判断我自定义的header而base中用的是final定义的

**Comment by huxq17** [comment]
你可以重写getAdapterItemViewType(position)

**Comment by 1181631922** [comment]
知道了，如果我把你的源码进行修改会对框架造成影响么？

**Comment by huxq17** [comment]
会有影响，你是出于什么需求需要重写这个方法

**Comment by 1181631922** [comment]
我试了会有，我的recyclerview需要加一个头，我在我的adapter中重写了onAttachedToRecyclerView这个周期，我重写了你说的getadapteritemviewtype位置不会有影响，但是布局会有影响，我的是gridview的Layoutmanager，两列的，但是头是一列，可以跟着recyclerview一起滑动，
 @Override
    public void onAttachedToRecyclerView(RecyclerView recyclerView) {
        super.onAttachedToRecyclerView(recyclerView);
        RecyclerView.LayoutManager manager = recyclerView.getLayoutManager();
        if (manager instanceof GridLayoutManager) {
            final GridLayoutManager gridManager = ((GridLayoutManager) manager);
            gridManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                @Override
                public int getSpanSize(int position) {
                    return getItemViewType(position) == TYPE_HEADER ? gridManager.getSpanCount() : 1;
                }
            });
        }
    }

**Comment by huxq17** [comment]
你看看demo里的BannerRecyclerViewActivity，这个是可以的做到你说的效果

**Comment by 1181631922** [comment]
看了下，差不多，不行我就改改，谢谢你

**Comment by 1181631922** [comment]
可以了，而且你框架的header和footer不会影响position，尤其item有点赞收藏的不用再去特殊考虑了，挺好的，赞个，我再熟悉一下
