### ISSUE TITLE
关于上拉加载状态

### ISSUE THREAD

**Issue by 1181631922** [huxq17/XRefreshView#23]
我看了一下代码，现在如果这是上拉自动加载的话，框架是不会判断是否footer全部显示才加载，只要拉到底部就加载，ui的话progressbar只要显示就是转动的，貌似没有一个prepare状态，简单来说就是和下拉刷新一样，拉到footer全部显示再进行动画显示，isShowing()判断的话只要是显示一点就为true，我理解的对么？

**Comment by huxq17** [comment]
嗯，自动加载更多，只要footer能被看到就会自动加载，isShowing和show方法应该是固定的写法，show方法只不过把隐藏footer的方式交给你自定义。你有什么需求需要改这方面的东西？

**Comment by 1181631922** [comment]
后来我仔细看了下，上拉加载拉动的最大距离是固定的，不支持回弹，这样的话上拉加载动画感觉就可以不管的，原本需求是上拉加载距离随意，用户拉动的时候loading不是动图，只是第一帧，松开回弹到固定距离的时候开始动画，加载完成以后停止动画，不过这样感觉也可以，用户体验影响不是很大，不过你可以当个建议，麻烦了
