### ISSUE TITLE
插件能否做到上拉至一定高度再释放才加载更多？

### ISSUE THREAD

**Issue by act64** [huxq17/XRefreshView#26]
不知道插件能否实现这个需求？至少对于footView开放一些可扩展的接口吧。

**Comment by huxq17** [comment]
目前recyclerview做不到，其他的默认就是这样

**Comment by act64** [comment]
这个高度能否自定义，问题可能描述的不是很清楚，不好意思.

我看您代码里面，只要view 到了底部，在滚动距离大于0，就会自动loadmore，这个滚动距离我想定制，但是代码里面没有开放public方法，不知道该怎么玩了？谢谢

**Comment by act64** [comment]
3.1.1有OFFSET_RADIO啊，点赞

**Comment by huxq17** [comment]
定制什么滚动距离？没怎么看懂，你看到的代码在哪？能贴出来么

**Comment by act64** [comment]
没事了，我把产品干掉了。。。。
不过能否设置一个 setMoveFootWhenDisablePullLoadMore(),就是在禁用 loadmore时，可选禁止上拉的阻尼效果

大概就是
``
 private void updateFooterHeight(int deltaY) {
        if (mState != XRefreshViewState.STATE_READY && mEnablePullLoad && !autoLoadMore) {
            mFooterCallBack.onStateReady();
            mState = XRefreshViewState.STATE_READY;
        }
        if (!(!mEnablePullLoad&&!mCanMoveFoot ) ){
            moveView(deltaY);
        }
    }
``

**Comment by huxq17** [comment]
3.1.2已经有了setMoveFootWhenDisablePullLoadMore
