### ISSUE TITLE
下拉刷新XScrollView与左右滑动的ViewPage冲突

### ISSUE THREAD

**Issue by MrSimpleX** [huxq17/XRefreshView#31]
下拉刷新XScrollView与左右滑动的ViewPage冲突，触发下拉操作的时候无法左右切换ViewPager，大神求解决方法啊~~

**Comment by huxq17** [comment]
触发下拉刷新的时候，事件就已经被XRefreshView接收了，viewpager不能左右切换很正常

**Comment by zouxianbincc** [comment]
试过它吗？作者说是用于解决布局里还有其他滑动事件的 xRefreshView.setMoveForHorizontal(true);

**Comment by tang5011235** [comment]
请问这个和轮播的ViewPager会冲突吗？

**Comment by huxq17** [comment]
@tang5011235 配置下xRefreshView.setMoveForHorizontal(true);就不会冲突了。
