### ISSUE TITLE
初始化设置参数问题

### ISSUE THREAD

**Issue by zouxianbincc** [huxq17/XRefreshView#34]
private Runnable mLoadingRunnable = new Runnable() {

        @Override
        public void run() {
            initVariables();
            initView();
            initDataAndLoadData();

        }
    };

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

     //省略设置布局
      

        getWindow().getDecorView().post(() -> mHandler.post(mLoadingRunnable));

    }

在initView()里才设置XRefreshView相关的设置。是无效的。

**Comment by huxq17** [comment]
哪些设置是无效的？我看看有没有必要改

**Comment by zouxianbincc** [comment]
按我上面的设置初始参数。footerview 显示异常。

**Comment by huxq17** [comment]
参数在哪？

**Comment by zouxianbincc** [comment]
3.5.2 版本已经解决。
