### ISSUE TITLE
无用的log

### ISSUE THREAD

**Issue by WillSprint** [huxq17/XRefreshView#35]
输出了太多无用的log,请问有没有开关

**Comment by huxq17** [comment]
有，LogUtils.allowD = false;

**Comment by WillSprint** [comment]
看了下源码，里面好像不止用LogUtils打印的log XRefreshView中有直接用Log打印的。例如： Log.d("CustomView", "add footView" + ";mHeaderViewHeight=" + mHeaderViewHeight);

**Comment by huxq17** [comment]
哪个文件里的，多少行？

**Comment by huxq17** [comment]
3.5.6版本添加了开关， LogUtils.enableLog(false);这样就可以关掉所有log
