### ISSUE TITLE
上拉加载更多的问题

### ISSUE THREAD

**Issue by luogan1234** [huxq17/XRefreshView#36]
ViewPager下，在XScrollView中，如果设置setAutoLoadMore(false)，在内容在竖直方向上并未撑满一个窗口时，将无法上拉加载，而设置setAutoLoadMore(true)，在内容未撑满一个窗口或恰好位于内容的底部时左右切换视图也会触发加载更多。
把XRefreshContentView.java中的canChildPullUp方法中的scrollView.getScrollY() != childView.getHeight() - scrollView.getHeight();改成<似乎能解决这个问题

**Comment by huxq17** [comment]
我看看

**Comment by huxq17** [comment]
非常感谢你的建议，已经把你的建议更新到代码里了。但是 **_在内容未撑满一个窗口或恰好位于内容的底部时左右切换视图也会触发加载更多。_** 这个问题我没有复现，demo中scrollview那个页面已经做成viewpager的了，你看看有没有你说的问题，或者怎么才能复现你的那个问题

**Comment by huxq17** [comment]
@luogan1234

**Comment by luogan1234** [comment]
这两个问题都是因为!=会造成内容不够时是否到底部的判断出现问题，我在实际用的时候改成<就不再产生这两个问题了，应该改那个地方就行了。
当时我是一个ViewPager下有一些Fragment，每个Fragment就一个linearlayout放了点文本，左右切换Fragment会触发我说的第二个问题。

**Comment by huxq17** [comment]
在3.5.2版本中已经解决了这个问题。其实有一种用法是自己可以去判断什么时候进行上拉和下拉，[参考这个类](https://github.com/huxq17/XRefreshView/blob/master/app/src/main/java/com/andview/example/activity/CustomViewActivity.java)
