### ISSUE TITLE
与com.youth.banner框架滑动冲突

### ISSUE THREAD

**Issue by aoguo** [huxq17/XRefreshView#43]
与com.youth.banner滑动冲突
https://github.com/youth5201314/banner

**Comment by huxq17** [comment]
有添加这行代码么xRefreshView.setMoveForHorizontal(true);

**Comment by aoguo** [comment]
因为嵌入了viewpager,加上xRefreshView.setMoveForHorizontal(true)这句后,不能通过滑动切换tab页了

**Comment by huxq17** [comment]
能给个有问题的demo看看么？

**Comment by aoguo** [comment]
等下写个简单的demo发你

**Comment by aoguo** [comment]
可能是其他问题引起的
