### ISSUE TITLE
无法设置上拉加载更多

### ISSUE THREAD

**Issue by Van1996** [huxq17/XRefreshView#44]
在ViewPager中的一个Fragment中，已使用XRefreshView嵌套一个RecyclerView
该RecyclerView能正常下拉刷新，但无法上拉加载更多
已设置  refreshView.setPullLoadEnable(true);

最后，为什么不做一个简单的demo呢 。

**Comment by huxq17** [comment]
你把这项目下载下来，然后跑到手机上就可以看效果了，这项目就是demo

**Comment by Van1996** [comment]
问题已解决，原因是Adapter没写正确，具体原因不能说得很清楚，是整个Adapter都写得很乱，模仿着demo写就好了
Thx
