### ISSUE TITLE
请教一个关于上拉加载的问题

### ISSUE THREAD

**Issue by aoguo** [huxq17/XRefreshView#45]
使用listview时,上拉加载后,显示加载状态,加载好数据后,加载状态消失,最后一行item会回弹到底部,是否可设置让新数据出现在加载状态那行,最后的item不回弹到底部,类似图片动画的效果

**Comment by huxq17** [comment]
上拉加载的这个效果只有recyclerview支持，别的都不支持。

**Comment by aoguo** [comment]
好的,thanks
