### ISSUE TITLE
xRefreshView.setLoadComplete(false)抛异常

### ISSUE THREAD

**Issue by f00cus** [huxq17/XRefreshView#47]
java.lang.RuntimeException: Recylerview的adapter请继承 BaseRecyclerAdapter

不知道什么情况？

**Comment by f00cus** [comment]
Adapter已经继承BaseRecyclerAdapter了，是参考demo写的

**Comment by huxq17** [comment]
给个有问题的demo看看。

**Comment by f00cus** [comment]
找到原因了，在调用这个方法的时候还没setAdapter
