### ISSUE TITLE
XScrollView在数据拉到最底的时候，点击屏幕会自动加载更多

### ISSUE THREAD

**Issue by Christy001** [huxq17/XRefreshView#49]
XScrollView在数据拉到最底的时候（设置了自动加载并且已经没有数据了），
点击屏幕会自动加载更多，哪怕是点击recycleView的item查看详情（页面跳转），该页面都会自动加载

**Comment by huxq17** [comment]
解决了，升级到3.5.8试试。

**Comment by Christy001** [comment]
OK，多谢仁兄！

**Comment by liqiangdada** [comment]
首先感谢大大写出这么优秀的框架来， 比之前用的某框架好用多了， 但是有个问题，XRefreshView 上拉时会失效， 下拉刷新正常，请问为什么

**Comment by huxq17** [comment]
上拉失效是什么情况？
