### ISSUE TITLE
加载更多数据完成之后返回位置问题

### ISSUE THREAD

**Issue by Riky-lee** [huxq17/XRefreshView#5]
能问一下，加载更多数据完成之后返回位置，并不是数据加载起始位置，而是返回到最顶部，使用setSelection 控制无效，这是什么原因导致的吗

**Comment by huxq17** [comment]
你刷新的view是什么，Recyclerview么？

**Comment by Riky-lee** [comment]
我使用的Gridview  ，结构如下
<com.andview.refreshview.XRefreshView
        android:id="@+id/xRefresh_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent">

        <GridView xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/grid"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:horizontalSpacing="6dp"
            android:stretchMode="columnWidth"
            android:numColumns="3"
            android:verticalSpacing="6dp"
            android:padding="2dp">
        </GridView>
    </com.andview.refreshview.XRefreshView>

但是  使用
new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {

                        //TODO  定位数据加载位置
                        long ansId = -1;

                        if (list != null && list.size() > 0) {
                            EyeRecg eyeRecg = list.get(list.size()-1);
                            ansId = eyeRecg.getId();
                        }

                        new ImageListThread(loadMoreHandler, 1, ansId).start();


                        gridView.setSelection(gridView.getLastVisiblePosition());
                        outView.stopLoadMore();

                        /*outView.setLoadComplete(true);*/

                    }
                }, 2000);
加载完数据之后无法定位到数据加载位置，而是直接返回最顶部

**Comment by huxq17** [comment]
gridview加载更多完成以后，不会露出部分新的加载更多数据，这个问题可以通过使用gridlayout样式的Recyclerview来解决。

**Comment by liuxing917738** [comment]
我也遇到了同样的问题,用的是listview,没有使用recyclerView.

坚持使用listview,有什么办法可以解决这个位置跳到最上面的吗?

**Comment by aoguo** [comment]
要是支持listview,这个框架就完美了

**Comment by huxq17** [comment]
现在listview和gridview都支持了，版本呢是3.5.6。
