### ISSUE TITLE
android.widget.RelativeLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams

### ISSUE THREAD

**Issue by Christy001** [huxq17/XRefreshView#52]
仁兄，今天项目运行的时候崩溃了，崩溃日志如下，麻烦仁兄看一下：
![qq 20170109163010](https://cloud.githubusercontent.com/assets/24953666/21760680/f34adf2c-d688-11e6-8c70-09f2efc30bd3.png)

**Comment by huxq17** [comment]
问题怎么出来的？

**Comment by Christy001** [comment]
我在项目的首页用到了这个控件，有时候打开的时候就崩溃了，看log日志是这样说的，但是后来又正常了！

**Comment by Christy001** [comment]
后来在RecycleView外面套了一层相对布局就好了
