### ISSUE TITLE
xrefreshview+banner+tablayout+viewpager时,上滑使tab固定在顶部问题

### ISSUE THREAD

**Issue by 900326** [huxq17/XRefreshView#57]
有个需求,xrefreshview+banner+tablayout+viewpager时,上滑使tab固定在顶部问题,但是无论是 使用系统的CoordinatorLayout还是第三方的都不行或是有其他新问题(试过很多),如下图效果,求解决[https://raw.githubusercontent.com/CarGuo/linkagescroll/master/device-2016-11-10-151539.gif](url)

**Comment by huxq17** [comment]
写个有问题的demo出来，我看看。

**Comment by 900326** [comment]
问题和我测试的demo发你邮箱了,麻烦有时间看下,求帮助,谢谢
