### ISSUE TITLE
XRefreshView作为FrameLayout子布局，不显示问题

### ISSUE THREAD

**Issue by 790770679** [huxq17/XRefreshView#58]
<FrameLayout
        android:id="@+id/hairpin_records_index_statelayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <com.andview.refreshview.XRefreshView
            android:id="@+id/hairpin_records_xrv"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            xrefreshview:isHeightMatchParent="true"
            xrefreshview:isWidthMatchParent="true">

            <ListView

                android:id="@+id/hairpin_records_index_lv_record"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </com.andview.refreshview.XRefreshView>
    </FrameLayout>
如上面的布局代码（FrameLayout本来是个加载状态的控件StateLayout,然后改成FrameLayout也出现同样问题），当设置FrameLayout为Gone,给列表数据，然后在设置FrameLayout为VISIABLE时，列表未出现。只有下拉一下才会出现列表。
麻烦看一下，谢谢。

**Comment by huxq17** [comment]
你用Relativelayout试试。

**Comment by huxq17** [comment]
3.6.1版本已经解决这个问题，你换下版本。
