### ISSUE TITLE
设置自带的footer之后还是不显示

### ISSUE THREAD

**Issue by kuailewangzi0328** [huxq17/XRefreshView#6]
rvProductRefresh.setCustomFooterView(new XRefreshViewFooter(getActivity()));

设置了这个，但是拉到底还是无法显示footer。另外，弱弱的说一下，能不能提供一个logEnable的函数来关闭log打印？刷屏刷的都看不清东西了……跳到代码看了一下你用的LogUtils这个类都没提供关闭的log的函数……只能改allowD这几个静态值

**Comment by huxq17** [comment]
你看了demo里面显示footerview的代码了么？xRefreshView.setPullLoadEnable(true);这行代码有添加么？library打印的日志都是d级别的，你过滤掉d级别就可以了，关的话可以把allowD这个值设为false;

**Comment by kuailewangzi0328** [comment]
找到原因了……在咱们这个控件上，如果之前设置了不允许上/下拉，那么在下面代码设置header/footer就会是无效的，即使你又重新设置为允许上/下拉，还是不会显示header/footer；

然后，如果设置了允许上/下拉，并成功设置了header/footer。然后在后面的代码中修改设置，变成不允许上/下拉，那么header/footer还是会在拉动的时候显示，只不过不会有状态的变化。

我不知道您是否认为这是个bug。不过我个人感觉这个应该是有问题的。理想的表现应该是，无论之前是否设置了允许与否，设置header/footer都不应该受到影响。 并且设置header/footer之后，如果之后禁用了上/下拉，那么在用户拉动的时候，就不应该显示相应的header/footer了……

**Comment by huxq17** [comment]
这些设置允许下拉上拉的方法都是在view初始化之前调用的，所以，如果一开始没有允许设置加载更多，那么footerview是没有被add进去的。你给的建议我考虑下，有结果了再来告诉你

**Comment by huxq17** [comment]
已经更新，可以自由设置允许和禁止下拉/上拉了。
