### ISSUE TITLE
Recylerview的adapter请继承 BaseRecyclerAdapter

### ISSUE THREAD

**Issue by SmallDream** [huxq17/XRefreshView#63]
现在项目中使用的是一套写好的adpter,继承Recylerview.Adpater. 如果改成BaseRecyclerAdapter 改动会很大。 作者可以让Recylerview.Adpater也正常使用吗，哪怕不支持某些特性也行，现在这样局限性有点大。

**Comment by huxq17** [comment]
如果不用BaseRecyclerAdapter,上拉加载更多就没法使用

**Comment by SmallDream** [comment]
其实没法使用也关系，因为项目中已经有一套写好的recylerview和对应的adpter来做这事。现在需要的是一个能支持recyclerview下拉刷新的控件。 可现在控件检测到不是继承自BaseRecyclerAdapter的话，就直接抛出异常。感觉这种情况可以按照一般的recylerview来处理。 个人意见，仅供参考。

**Comment by huxq17** [comment]
嗯，我看看

**Comment by huxq17** [comment]
已经可以了，示例在github上的demo里，路径 Recyclerview —>不使用BaseRecyclerAdapter，代码在WithoutBaseAdapterRecyclerViewActivity里。详见README中更新日志2017-3-28。

**Comment by SmallDream** [comment]
多谢啦。现在这样确实灵活多了。
