### ISSUE TITLE
mAdapter.setCustomLoadMoreView(new XRefreshViewFooter(this))问题

### ISSUE THREAD

**Issue by Huangzhe** [huxq17/XRefreshView#64]
使用mAdapter.setCustomLoadMoreView(new XRefreshViewFooter(this));
但出现的footerView 为什么是一条默认的RecyleView的Item？
我的设置：

         recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(mAdapter);
        mXRefreshView.setCustomHeaderView(new CustomHeaderView(this));
       mXRefreshView.setPinnedTime(1000);
        mXRefreshView.setMoveForHorizontal(true);
        mXRefreshView.setPullLoadEnable(true);
        mXRefreshView.setAutoLoadMore(false);        
        mAdapter.setCustomLoadMoreView(new XRefreshViewFooter(this));
        mXRefreshView.enableReleaseToLoadMore(true);
        mXRefreshView.enableRecyclerViewPullUp(true);
        mXRefreshView.enablePullUpWhenLoadCompleted(true);
        mXRefreshView.setXRefreshViewListener(new XRefreshView.SimpleXRefreshListener()

**Comment by huxq17** [comment]
see #65
