### ISSUE TITLE
BaseRecyclerAdapter和Butterknife冲突，这个怎么解决？

### ISSUE THREAD

**Issue by Huangzhe** [huxq17/XRefreshView#65]
冲突点在这个方法  
@Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {}

   如果不再重写这个方法，Butterknife报错，如果重写，加载footer则显示为RecyleView的一个默认Item

**Comment by huxq17** [comment]
你看看demo里的用法，重写的onCreateViewHolder有三个参数

**Comment by Huangzhe** [comment]
如果只用三个参数的onCreateViewHolder，而不加上两个参数的，Butterknife报错

**Comment by huxq17** [comment]
什么错？

**Comment by Huangzhe** [comment]
找不到View 的 id

**Comment by huxq17** [comment]
这和xrefreshview关系不大，建议把github上的demo下载下来看看。不继承BaseRecyclerAdapter也可以，详见[Recylerview的adapter请继承 BaseRecyclerAdapter](https://github.com/huxq17/XRefreshView/issues/63)
