### ISSUE TITLE
只要下拉刷新,不要上拉加载.

### ISSUE THREAD

**Issue by liuxing917738** [huxq17/XRefreshView#7]
只要下拉刷新,不要上拉加载.

我设置了取消上拉刷新,只要下拉刷新,但是进入界面的时候还是可以上拉刷新.

public void setRefreshData(boolean pullLoadMore, boolean autoRefresh) {
        refreshView.setPullLoadEnable(pullLoadMore);
        refreshView.setAutoLoadMore(false);
        refreshView.setAutoRefresh(autoRefresh);
        refreshView.setXRefreshViewListener(new XRefreshView.SimpleXRefreshListener() {
            @Override
            public void onRefresh() {
                refreshData();
            }

```
        @Override
        public void onLoadMore(boolean isSlience) {
            loadMoreData();
        }

    });
}
```

调用setRefreshData(false, true); 调用该方法还是会出现上拉加载更多的界面. 求解决方案

**Comment by huxq17** [comment]
你刷新的是什么view，Recyclerview还是什么？如果是的话，你更新到2.0.5看看。

**Comment by liuxing917738** [comment]
刷新的是普通的xscrollview嵌套的图片和Listview

**Comment by huxq17** [comment]
我试了下是正常的，你升级到2.0.5试试，如果还不行，方便的话写个demo给我看看

**Comment by liuxing917738** [comment]
我试试看,有什么情况再反馈.谢谢 了

**Comment by 1181631922** [comment]
有没有想过在xml中进行可配置上拉加载和下拉刷新？

**Comment by huxq17** [comment]
@1181631922 还没有，感觉意义不大
