### ISSUE TITLE
XRefreshView 高度小于屏幕高度时， XRefreshView  底部会比 RecyclerView 多出一部分

### ISSUE THREAD

**Issue by yongyu0102** [huxq17/XRefreshView#75]
楼主你好，XRefreshView 高度小于屏幕高度时， XRefreshView  底部会比 RecyclerView 多出一部分无法隐藏

**Comment by huxq17** [comment]
多一部分是什么意思？

**Comment by huxq17** [comment]
3.6.8版本已经解决了这个问题

**Comment by ligas1994** [comment]
listview 没有满屏时 footer还是会自动显示， 添加自定义footer 也没用
