### ISSUE TITLE
XRefreshView里拿到listview

### ISSUE THREAD

**Issue by yunye121** [huxq17/XRefreshView#77]
getContentView().getContentView()
我看代码XRefreshContentView返回来的应该是一个abslistview,但是我拿到的一直是relativelayout ,不知道为什么,求大神解答

**Comment by huxq17** [comment]
你是不是设置了emptyview，并且调用了enableEmptyView(true)？emptyview是Relativelayout？

**Comment by yunye121** [comment]
是设置了emptyview并让它显示了,这样怎么拿到listview?设置了emptyview没让它显示怎么拿到listview?

**Comment by huxq17** [comment]
listview不能直接通过findviewbyid来获取么？

**Comment by yunye121** [comment]
是这样的,我写了一个类来继承XRefresh,把我们用到的一些属性设置一下,我还设置了emptyview,在onRefresh和onLoadMore的时候如果能获取listview就能获取adapter就能获取count,判断count数量就能设置enableEmptyView(true)不用每次在activity中设置了

**Comment by huxq17** [comment]
方法有很多，你可以重写onFinishInflate方法，在这里面getChildAt(1)就是listview

**Comment by yunye121** [comment]
好的,非常感谢
