### ISSUE TITLE
已无更多数据显示不出来

### ISSUE THREAD

**Issue by Christy001** [huxq17/XRefreshView#78]
refreshView.setCustomHeaderView(new XRefreshViewHeader(WorkTrendsFragment.this.getActivity()));
refreshView.setCustomFooterView(new XRefreshViewFooter(WorkTrendsFragment.this.getActivity()));
refreshView.setXRefreshViewListener(onXRefreshViewListener);

上面我设置了footer,在下面上拉加载的时候我也判断了
@Override
public void onLoadMore(boolean isSilence) {
    try {
        refreshView.postDelayed(new Runnable() {
            @Override
            public void run() {
                currentPage = ++currentPage;
                isFirstLoading = false;
                loadData(false, currentPage, 10);
                if (workTrendsList.size() < currentPage*pageSize) {
                    refreshView.setLoadComplete(true);
                } else {
                    // 刷新完成必须调用此方法停止加载
                    refreshView.stopLoadMore();
                }
             }
         }, 1000);
     } catch (Exception e) {
          e.printStackTrace();
     }
 }
为什么“没有更多数据”没有显示出来，footer直接就隐藏了

**Comment by huxq17** [comment]
等一等，确实有这个问题。

**Comment by huxq17** [comment]
你更新到3.6.9版本看看。

**Comment by Christy001** [comment]
我打了断点试了下，能够进到footer的onStateComplete方法中，但是“已没有更多数据了”还是没有在界面上显示出来，抽时间我做个demo发给你，你再看看，不知道是不是我代码的问题。另外，在没有数据的时候能不能让“已没有更多数据了”显示在底部，不要隐藏footer了，貌似现在好多APP都是这样的，像支付宝

**Comment by Christy001** [comment]
我搞了个简单的demo，已经发送到你的163邮箱了，麻烦你抽空看下

**Comment by huxq17** [comment]
加上refreshView.setPinnedTime(1000);如果不设置footerview固定的时间，footview立马就被隐藏了，所以会看不到效果。
