### ISSUE TITLE
XRefreshView中嵌套了一个webview，webview拉到中间后，再向下滑动，出现headview，有什么办法webview到头部后在向下滑动出现刷新view么

### ISSUE THREAD

**Issue by DarksKnight** [huxq17/XRefreshView#79]
XRefreshView中嵌套了一个webview，webview拉到中间后，再向下滑动，出现headview，有什么办法webview到头部后在向下滑动出现刷新view么

**Comment by huxq17** [comment]
能提供个复现问题的例子么？感觉不可能啊

**Comment by DarksKnight** [comment]
@huxq17 我的github里，有工程，hnplatform。。。

**Comment by huxq17** [comment]
你用的是腾讯的webview，相当于是自定义view了，上下滑动的时候他的mScrollY返回总是0，导致xrefreshview判断到达顶部的条件总是true，这时候就得自己通过setOnTopRefreshTime方法设置到达顶部的时机了，我看了他的源码，有个替代的getWebScrollY()方法能使用。具体的用法如下：
 xr.setOnTopRefreshTime(new OnTopRefreshTime() {
            @Override
            public boolean isTop() {
                return bwvContent.getWebScrollY()==0;
            }
        });

**Comment by DarksKnight** [comment]
好的，谢谢了，我看下
