### ISSUE TITLE
'boolean com.andview.refreshview.XRefreshView.hasLoadCompleted()' on a null object reference

### ISSUE THREAD

**Issue by liuxing917738** [huxq17/XRefreshView#8]
else if (null == mContainer) {
                            if (!mIsLoadingMore && isOnRecyclerViewBottom()) {
                                refreshAdapter(adapter, layoutManager);
                                if (!mContainer.hasLoadCompleted()) {
                                    if (mState != XRefreshViewState.STATE_READY) {
                                        mFooterCallBack.onStateReady();
                                        setState(XRefreshViewState.STATE_READY);
                                    }
                                } else {
                                    loadCompleted();
                                }
                            } else {
                                setState(XRefreshViewState.STATE_NORMAL);
                            }
                        }

按照你的Master中的demo去写.  发现项目能加载成功,但是上拉到底部的时候是直接报错.

null == mContainer为空的时候再去调用方法  if (!mContainer.hasLoadCompleted()) { }肯定是会报错的

求解.

**Comment by liuxing917738** [comment]
已找到解决办法:

if (!mContainer.hasLoadCompleted()) {

需要注释这行.

**Comment by huxq17** [comment]
你怎么注释的？如果直接注释掉，那么
xRefreshView.setLoadComplete(true);
这行代码就没有了作用，我已经解决了这个问题，版本升到2.0.6了，感谢你的关注！
