### ISSUE TITLE
updateHeaderHeight需要加上一个条件

### ISSUE THREAD

**Issue by superstapler** [huxq17/XRefreshView#80]
XReFreshView 470行,
if (!mPullLoading && !mReleaseToLoadMore && mContentView.isTop() && ((deltaY > 0 && !mHolder.hasFooterPullUp()) || (deltaY < 0 && mHolder.hasHeaderPullDown()))) {
                    sendCancelEvent();
                    updateHeaderHeight(currentY, deltaY);
                }
需要加上mEnablePullRefresh这个条件,否则与AppbarLayout结合使用时有问题.

**Comment by huxq17** [comment]
不需要，加上下面的代码就可以了。
appBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
            @Override
            public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
                isTop = verticalOffset == 0;
            }
        });
       xrefreshView.setOnTopRefreshTime(new OnTopRefreshTime() {
            @Override
            public boolean isTop() {
                return isTop;
            }
        });
