### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by kulong51** [huxq17/XRefreshView#83]
有个问题想请教下， 如果我上拉加载完成设置了setLoadComplete(true) 已经不能再上拉加载了， 这时候只能重新下拉刷新，能否设置上拉加载完成已无更多数据，还可以上拉加载数据呢？

**Comment by huxq17** [comment]
在调用setLoadComplete(false)就好了。

**Comment by kulong51** [comment]
ok，谢谢了

发自我的vivo智能手机

huxq17 <notifications@github.com>编写：
