### ISSUE TITLE
请问，当时用了isTop判断，现在页面中overflow:hidden的情况，导致了不能滑动了。

### ISSUE THREAD

**Issue by DarksKnight** [huxq17/XRefreshView#87]
有什么办法可以解决的。
rl.setOnTopRefreshTime(new OnTopRefreshTime() {
            @Override
            public boolean isTop() {
                return bwvContent.getScrollY() == 0;
            }
        });
当时是这么做判断的。

**Comment by huxq17** [comment]
这里在到达顶部的时候返回true就行了，你得根据情况设置条件。

**Comment by DarksKnight** [comment]
比较蛋疼的是，overflow为hidden的div就是在顶部的。。。所以才不能被滑动。。有什么好的解决办法么。

**Comment by huxq17** [comment]
不清楚，html不是很熟

**Comment by DarksKnight** [comment]
解决了，需要网页配合，自己本身无法获取到网页标签的滑动事件。
