### ISSUE TITLE
下拉刷新的时候，松开手指head立马回弹了

### ISSUE THREAD

**Issue by wsy858** [huxq17/XRefreshView#9]
试了作者的示例，都是只要一松开手指，立马head就回弹，并没有等待网络刷新完成，请问该如何设置？

**Comment by huxq17** [comment]
已经解决了，你试下
compile 'com.huxq17.xrefreshview:xrefreshview:2.1.4'

**Comment by wsy858** [comment]
谢谢，正打算项目使用，回复的很及时，辛苦了。
