### ISSUE TITLE
Refreshview+CoordinatorLayout +AppBarLayout+RecyclerView 有事件冲突

### ISSUE THREAD

**Issue by zouxianbincc** [huxq17/XRefreshView#92]
XRefreshview+CoordinatorLayout +AppBarLayout+RecyclerView 有事件冲突
想做的效果是，XRefreshview放在最外层CoordinatorLayout，滑动RecyclerView ，当往下滑时，滑到最顶部时，启动下拉刷新。如果往上滑动。AppBarLayout固定

**Comment by huxq17** [comment]
@zouxianbincc 说说怎么解决的

**Comment by zouxianbincc** [comment]
解决了，在CoordinatorLayout 外放 XRefreshView ，把固定在顶部的view  放在 AppBarLayout里，列表部分，要用NestedScrollView.
主要是要添加AppBarLayout 的监听 addOnOffsetChangedListener

        appBarLayout.addOnOffsetChangedListener(new AppBarLayout.OnOffsetChangedListener() {
            @Override
            public void onOffsetChanged(AppBarLayout appBarLayout, int verticalOffset) {
                isTop = verticalOffset == 0;
            }
        });
然后添加XRefreshView 滑动到顶部刷新时机，
        xrefreshView.setOnTopRefreshTime(new OnTopRefreshTime() {
            @Override
            public boolean isTop() {
                if(isFirst){
                    isFirst = false;
                    return  false;
                }
                return isTop;
            }
        });
